# Generated by Django 5.1.7 on 2025-05-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={'ordering': ['uid']},
        ),
        migrations.AlterModelOptions(
            name='hotelimages',
            options={'ordering': ['uid']},
        ),
    ]
